SELECT r.RDB$FIELD_NAME,
    CASE f.RDB$FIELD_TYPE
        WHEN 261 THEN 'BLOB'
        WHEN 14 THEN 'CHAR'
        WHEN 40 THEN 'CSTRING'
        WHEN 11 THEN 'D_FLOAT'
        WHEN 27 THEN 'DOUBLE'
        WHEN 10 THEN 'FLOAT'
        WHEN 16 THEN 'INT64'
        WHEN 8 THEN 'INTEGER'
        WHEN 9 THEN 'QUAD'
        WHEN 7 THEN 'SMALLINT'
        WHEN 12 THEN 'DATE'
        WHEN 13 THEN 'TIME'
        WHEN 35 THEN 'TIMESTAMP'
        WHEN 37 THEN 'VARCHAR'
        ELSE 'UNKNOWN' END
    AS field_type,
    f.RDB$CHARACTER_LENGTH AS field_length,
    f.RDB$FIELD_PRECISION AS field_precision,
    f.RDB$FIELD_SCALE AS field_scale,
       REVERSE(SUBSTRING(REVERSE(SUBSTRING(trim(r.RDB$DEFAULT_SOURCE) FROM CHAR_LENGTH('DEFAULT') + 3)) FROM 2)) AS field_default_value,
    Case r.RDB$NULL_FLAG
        WHEN 1 THEN 1
        ELSE 0 END
    AS field_not_null_constraint,
    trim(cset.RDB$CHARACTER_SET_NAME) AS field_charset
FROM RDB$RELATION_FIELDS r
LEFT JOIN RDB$FIELDS f ON r.RDB$FIELD_SOURCE = f.RDB$FIELD_NAME
LEFT JOIN RDB$CHARACTER_SETS cset ON f.RDB$CHARACTER_SET_ID = cset.RDB$CHARACTER_SET_ID
WHERE r.RDB$RELATION_NAME='TEST'; -- Table Name